import turtle as hail
hail.speed(1)
hail.width(2)
hail.setup(1000,1000)
hail.title('3D Penrose Triangle')

def draw_penrose_triangle(x,y,size,tilt):
    hail.pencolor((0.2,0.2,0.2))
    hail.up()
    hail.goto(x,y)
    hail.seth(tilt)
    hail.down()
    hail.fd(size*2)
    p1x = hail.xcor()
    p1y = hail.ycor()
    p1a = hail.heading()
    hail.left(120)
    hail.fd(size*2)
    p2x = hail.xcor()
    p2y = hail.ycor()
    p2a = hail.heading()
    hail.left(120)
    hail.fd(size*2)
    p3x = hail.xcor()
    p3y = hail.ycor()
    p3a = hail.heading()
    # Gray Part
    hail.up()
    hail.goto(p1x,p1y)
    hail.seth(p1a)
    hail.down()
    hail.fillcolor('dark gray')
    hail.begin_fill()
    hail.fd(size)
    hail.left(120)
    hail.fd(size*5)
    hail.left(120)
    hail.fd(size*6)
    hail.left(60)
    hail.fd(size)
    hail.left(120)
    hail.fd(size*5)
    hail.right(120)
    hail.fd(3*size)
    hail.end_fill()
    #Black Part
    hail.up()
    hail.goto(p2x,p2y)
    hail.seth(p2a)
    hail.down()
    hail.fillcolor('black')
    hail.begin_fill()
    hail.fd(size)
    hail.left(120)
    hail.fd(5*size)
    hail.left(120)
    hail.fd(6*size)
    hail.left(60)
    hail.fd(size)
    hail.left(120)
    hail.fd(5*size)
    hail.right(120)
    hail.fd(3*size)
    hail.end_fill()
    #white
    hail.up()
    hail.goto(p3x,p3y)
    hail.seth(p3a)
    hail.down()
    hail.fd(size)
    hail.left(120)
    hail.fd(5*size)
    hail.left(120)
    hail.fd(6*size)
    hail.left(60)
    hail.fd(size)
    hail.left(120)
    hail.fd(5*size)
    hail.right(120)
    hail.fd(3*size)

draw_penrose_triangle(-80,-50,80,0)

hail.done()